### ISSUE TITLE
Expense Tracking section.

### ISSUE THREAD

**Issue by vikram0104irctc** [vikram0104irctc/Amazon-Avengers_076#28]
- [x] Create the Expense Tracking section.

- [x] Add progress bar.

- [x] Add animation inside the progress bar.

- [x] Add the images.

- [x] Make it responsive.
