### ISSUE TITLE
Savings Tracking section.

### ISSUE THREAD

**Issue by vikram0104irctc** [vikram0104irctc/Amazon-Avengers_076#29]
- [x] Create the Savings Tracking section.

- [x] Add progress bar.

- [x] Add animation inside the progress bar.

- [x] Give the monthly data.

- [x] Make it responsive.

**Comment by vikram0104irctc** [comment]
Good work by my team.
