### ISSUE TITLE
Income Tracking section.

### ISSUE THREAD

**Issue by vikram0104irctc** [vikram0104irctc/Amazon-Avengers_076#30]
- [x] Create the Income Tracking section.

- [x] Add progress bar.

- [x] Add animation inside the progress bar.

- [x] Add the images.

- [x] Make it responsive.

- [x] Add the monthly data.
